### ISSUE TITLE
Publishing new version is required to support Elixir 1.13

### ISSUE THREAD

**Issue by jechol** [witchcrafters/witchcraft#106]
https://github.com/witchcrafters/witchcraft/pull/101/commits/37e990b873a8fcc172341803303d60abec89decb

Above commit is required to support Elixir 1.13.

Please publish new package to hex.pm.

**Comment by QuinnWilton** [comment]
I've just published 1.0.4 with the required changes! The diff is available here: https://diff.hex.pm/diff/witchcraft/1.0.3..1.0.4

Thanks for your patience: I had started on upgrading all of the libraries over the weekend, and then life got in the way for a few days!

**Comment by jechol** [comment]
@QuinnWilton Thanks a lot. 

@expede gave me a merge permission for type_class and algae, but not for quark and witchcraft. 

Could you give me a merge permssion for the quark and witchcraft?
Because sometimes PR is pending without any review too long...

**Comment by QuinnWilton** [comment]
> Could you give me a merge permssion for the quark and witchcraft? Because sometimes PR was pending without any review too long...

It actually looks like you already have write permission for those. The audit logs don't show me when those were added, but it's possible that Brooklyn may have already done this!
