### ISSUE TITLE
unable to use witchcraft

### ISSUE THREAD

**Issue by jppic** [witchcrafters/witchcraft#92]
Hi there. 
Hopefully I am not mistaking by raising that kind of issue here. Forgive a newcomer please !
I am on macOS 12.0.1, Erlang/OTP 24, Interactive Elixir (1.12.3)
I was willing to experiment with this library. I followed instructions but I get the following message when running %iex -S mix : (trying suggestions did not help). 
Many thanks to whoever can help.
JP

== Compilation error in file lib/witchcraft/foldable.ex ==
** (CompileError) lib/witchcraft/foldable.ex:751: function then/2 imported from both Witchcraft.Apply and Kernel, call is ambiguous
    (elixir 1.12.3) src/elixir_dispatch.erl:42: :elixir_dispatch.import_function/4
    (elixir 1.12.3) src/elixir_fn.erl:76: :elixir_fn.capture_import/4
    (stdlib 3.16.1) lists.erl:1358: :lists.mapfoldl/3
    (stdlib 3.16.1) lists.erl:1359: :lists.mapfoldl/3
could not compile dependency :witchcraft, "mix compile" failed. You can recompile this dependency with "mix deps.compile witchcraft", update it with "mix deps.update witchcraft" or clean it with "mix deps.clean witchcraft"

**Comment by jppic** [comment]
I realize this issue might be the same as # 90

**Comment by florius0** [comment]
Use witchcraft from github rather then from hex. https://hexdocs.pm/mix/1.12/Mix.Tasks.Deps.html

**Comment by QuinnWilton** [comment]
This has been addressed with the new 1.0.4 release. Thank you for the report!

https://github.com/witchcrafters/witchcraft/issues/106
